import * as fs from 'fs';
import * as path from 'path';
import { TestPlan, TestCase, GenerationResult } from '../types';

/**
 * Extracts the first function signature line from a source file matching the
 * given function name. Falls back to a generic placeholder if not found.
 */
function extractSignature(source: string, functionName: string): string {
  const lines = source.split('\n');
  for (const line of lines) {
    if (line.includes(`function ${functionName}`) || line.includes(`${functionName}(`)) {
      return line.trim();
    }
  }
  return `function ${functionName}(/* unknown signature */)`;
}

/**
 * Renders the Jest assertion body for a single {@link TestCase}.
 */
function renderAssertion(plan: TestPlan, tc: TestCase): string {
  const call = `${plan.functionName}(${tc.inputs})`;
  switch (tc.type) {
    case 'happy':
      return [
        `    const result = ${call};`,
        `    expect(result).toBeDefined();`,
      ].join('\n');
    case 'edge':
      return [
        `    const result = ${call};`,
        `    expect(result == null || result === '' || (Array.isArray(result) && result.length === 0)).toBe(true);`,
      ].join('\n');
    case 'error':
      return `    expect(() => ${call}).toThrow();`;
  }
}

/**
 * Renders a complete Jest `it()` block for a single {@link TestCase}.
 */
function renderItBlock(plan: TestPlan, tc: TestCase): string {
  return [
    `  it('${tc.description}', () => {`,
    renderAssertion(plan, tc),
    `  });`,
  ].join('\n');
}

/**
 * Builds the full content of a Jest test file for a given {@link TestPlan}.
 */
function renderTestFile(plan: TestPlan, signature: string): string {
  const importPath = plan.filePath.replace(/\.[jt]sx?$/, '');
  const itBlocks = plan.testCases.map((tc) => renderItBlock(plan, tc)).join('\n\n');

  return [
    `// Auto-generated by TestForge — do not edit manually.`,
    `// Source signature: ${signature}`,
    ``,
    `import { ${plan.functionName} } from '${importPath}';`,
    ``,
    `describe('${plan.functionName}', () => {`,
    itBlocks,
    `});`,
    ``,
  ].join('\n');
}

/**
 * Generates Jest test files from {@link TestPlan} objects.
 */
export class TestWriter {
  /**
   * Writes a Jest test file for the given {@link TestPlan} to `outputDir`.
   *
   * The output path is:
   * `<outputDir>/__tests__/<basename>.generated.test.ts`
   *
   * The function reads the target source file to extract the function
   * signature before rendering the test template.
   *
   * @param plan      - The test plan describing the function and test cases.
   * @param outputDir - Directory under which the `__tests__` folder is created.
   * @returns A {@link GenerationResult} indicating success or failure.
   */
  async write(plan: TestPlan, outputDir: string): Promise<GenerationResult> {
    const ext = /\.tsx?$/.test(plan.filePath) ? 'ts' : 'js';
    const baseName = path.basename(plan.filePath, path.extname(plan.filePath));
    const outputFile = path.join(outputDir, '__tests__', `${baseName}.generated.test.${ext}`);

    let source = '';
    try {
      source = fs.readFileSync(plan.filePath, 'utf-8');
    } catch {
      return {
        filePath: plan.filePath,
        success: false,
        error: `Could not read source file: ${plan.filePath}`,
        testsGenerated: 0,
      };
    }

    const signature = extractSignature(source, plan.functionName);
    const content = renderTestFile(plan, signature);

    try {
      fs.mkdirSync(path.join(outputDir, '__tests__'), { recursive: true });
      fs.writeFileSync(outputFile, content, 'utf-8');
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        filePath: plan.filePath,
        success: false,
        error: `Could not write test file: ${message}`,
        testsGenerated: 0,
      };
    }

    return {
      filePath: plan.filePath,
      success: true,
      generatedPath: outputFile,
      testsGenerated: plan.testCases.length,
    };
  }
}
