// Auto-generated by TestForge — route handler integration tests.
// Source: ../../src/routes/users
const request = require('supertest');
const app = require('../../src/app');
describe('users routes', () => {
  describe('deleteUser', () => {
    it('responds to DELETE /api/users/:id', async () => {
      const res = await request(app).delete('/api/users/test-id');
      expect([200, 201, 204, 400, 404, 500]).toContain(res.status);
    });

    it('deleteUser returns 404 for unknown id', async () => {
      const res = await request(app).delete('/api/users/nonexistent-id-999');
      expect(res.status).toBe(404);
    });
  });
  describe('getUsersList', () => {
    it('responds to GET /api/users', async () => {
      const res = await request(app).get('/api/users');
      expect([200, 201, 204, 400, 404, 500]).toContain(res.status);
    });

    it('getUsersList returns 400 for invalid input', async () => {
      const res = await request(app).get('/api/users').send({});
      expect(res.status).toBe(400);
    });

    it('getUsersList returns 404 for unknown id', async () => {
      const res = await request(app).get('/api/users');
      expect(res.status).toBe(404);
    });
  });
  describe('getUserById', () => {
    it('responds to GET /api/users/test-id', async () => {
      const res = await request(app).get('/api/users/test-id');
      expect([200, 201, 204, 400, 404, 500]).toContain(res.status);
    });

    it('getUserById returns 400 for invalid input', async () => {
      const res = await request(app).get('/api/users/test-id').send({});
      expect(res.status).toBe(400);
    });

    it('getUserById returns 404 for unknown id', async () => {
      const res = await request(app).get('/api/users/test-id');
      expect(res.status).toBe(404);
    });
  });
  describe('createUser', () => {
    it('responds to POST /api/users', async () => {
      const res = await request(app).post('/api/users');
      expect([200, 201, 204, 400, 404, 500]).toContain(res.status);
    });

    it('createUser returns 400 for invalid input', async () => {
      const res = await request(app).post('/api/users').send({});
      expect(res.status).toBe(400);
    });

    it('createUser returns 404 for unknown id', async () => {
      const res = await request(app).post('/api/users');
      expect(res.status).toBe(404);
    });
  });
  describe('updateUser', () => {
    it('responds to PATCH /api/users/:id', async () => {
      const res = await request(app).patch('/api/users/test-id');
      expect([200, 201, 204, 400, 404, 500]).toContain(res.status);
    });

    it('updateUser returns 404 for unknown id', async () => {
      const res = await request(app).patch('/api/users/nonexistent-id-999');
      expect(res.status).toBe(404);
    });
  });
});